#!/bin/python

# This application is used for "pasting" a text (as if you have pressed ctrl + V) to a window of a virtual machine
# without guest additions or ip-kvm/ipmi iKVM viewer window.
#
# It asks you a string you want to input on a remote machine. Then you click a button, switch to
# the desired window, and then script similates typing on a keyboard.
#
# This is useful in situations when using guest additions is not possible, for example when you are rescuing a target system. You may simplify
# routine of retyping commands for mounting partitions and chrooting. Or at a grub screen you can easily "paste" a UUID of needed device to boot from.

import sys
import os
import subprocess

from PyQt5 import QtWidgets
import design

class ExampleApp(QtWidgets.QMainWindow, design.Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.simulateTypeButton.clicked.connect(self.simulate_typing)

    def simulate_typing(self):
        mytext = self.plainTextEdit.toPlainText()
        self.listWidget.addItem(mytext)
        subprocess.call(["sleep", "3"])
        subprocess.call(["xdotool", "type", mytext])

def main():
    app = QtWidgets.QApplication(sys.argv)
    window = ExampleApp()
    window.show()
    app.exec_()

if __name__ == '__main__':
    main()
