#!/bin/python

# This application is used for "pasting" a text (as if you have pressed ctrl + V) to a window of a virtual machine
# without guest additions or ip-kvm/ipmi iKVM viewer window.
#
# It asks you a string you want to input on a remote machine. Then you click a button, switch to
# the desired window, and then script similates typing on a keyboard.
#
# This is useful in situations when using guest additions is not possible, for example when you are rescuing a target system. You may simplify
# routine of retyping commands for mounting partitions and chrooting. Or at a grub screen you can easily "paste" a UUID of needed device to boot from.

import sys
import os
import subprocess
import datetime

from PyQt5 import QtWidgets
import design

windowid = "0"

class PasteTyperApp(QtWidgets.QMainWindow, design.Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.simulateTypeButton.clicked.connect(self.simulate_typing)
        self.select_window_btn.clicked.connect(self.choose_window)
        self.toolButton.clicked.connect(self.clear_text_area)

        self.statusBar().showMessage("Target window id: " + windowid)


    def simulate_typing(self):
        windowid = subprocess.check_output(["xdotool", "selectwindow"], universal_newlines=True)
        windowid = subprocess.check_output(["xdotool", "windowactivate", windowid], universal_newlines=True)
        mytext = self.plainTextEdit.toPlainText()
        self.listWidget.addItem(mytext)
        subprocess.call(["sleep", "0.5"])
        return_code = subprocess.call(["xdotool", "type", "--window", windowid, mytext])
        self.statusBar().showMessage("Target window id: " + windowid + "; Return code: " + str(return_code) + "; " + str(datetime.datetime.now()))


    def choose_window(self):
        windowid = subprocess.check_output(["xdotool", "selectwindow"], universal_newlines=True)
        self.statusBar().showMessage("Target window id: " + windowid)

    def clear_text_area(self):
        self.plainTextEdit.clear()

def main():
    app = QtWidgets.QApplication(sys.argv)
    window = PasteTyperApp()
    window.show()
    app.exec_()

if __name__ == '__main__':
    main()
